apps/presenthistory/urls.py
from django.urls import path
from .views import *


app_name = "presenthistory"
urlpatterns = [

    # Present History section
    path('create/present/history/patient/<int:patient_id>/visit/<int:visit_id>/',
        save_present_hist,
        name='save_present_hist'),

    path('present/history/patient/<int:patient_id>/visit/<int:visit_id>/edit/<int:id>/', 
        edit_present_hist, 
        name="edit_present_hist"),   

    path('present/history/table/',
        table_present_hist,
        name='table_present_hist'),
    #
    path('delete/present/history/<int:id>/',
        delete_history, 
        name="delete_history"),

    #
    path('present/history/patient/<int:patient_id>/',
        patient_history_table,
        name="patient_history_table"),
    #
    path('present/history/visit/<int:visit_id>/',
        visit_history_table, 
        name="visit_history_table"),

    #
    path('add/present/history/', 
        table_add_present_hist, 
        name="table_add_present_hist"),

]

apps/revisits/urls.py
from django.urls import path
from .views import *

app_name= "revisits"

urlpatterns = [
     path('create/revisit/patient/<int:patient_id>/visit/<int:visit_id>/',
        save_revisit,
        name='save_revisit'),
    #
    path('edit/revisit/<int:id>/patient/<int:patient_id>/visit/<int:visit_id>/', 
        edit_revisit, 
        name='edit_revisit'),    
    #
    path('table/revisits/', 
        table_revisit, 
        name='table_revisit'),
    #
    path('table/for/visit/<int:visit_id>/patient/<int:patient_id>/', 
        view_revisit, 
        name='view_revisit'),
    #
    path('delete/revisit/<int:id>/',
        delete_revisit, 
        name="delete_revisit"),
]

apps/search/urls.py
from django.urls import path
from .views import *

app_name= "search"

urlpatterns = [

    #
    path('search/patient/', search_patient, name='search_patient'),
    path('search/visit/', search_visit, name='search_visit'),
    path('search/date/', search_date, name='search_date'),
    path('search/only/date/', search_only, name='search_only'),

    #
    # path('income/day/<int:day>/<int:month>/<int:year>/', calculate_income, name='day_income'),
    # path('income/month/<int:day>/<int:month>/<int:year>/', calculate_income, name='month_income'),
    
    # path('income/year/<int:year>/', calculate_income, name='year_income'),
    
    # path('income/day/', calculate_income, name='calculate_day_income'),
    # path('income/month/', calculate_income, name='calculate_month_income'),
    
    # path('income/day/', calculate_day_income, name='calculate_day_income'),
    # path('income/month/', calculate_month_income, name='calculate_month_income'),
    # path('income/year/', calculate_year_income, name='calculate_year_income'),
    

]

apps/visitdrug/urls.py
from django.urls import path
from .views import *
from .prescription import *
app_name= "visitdrug"

urlpatterns = [
    #
    path('prescription/for/patient/<int:patient_id>/visit/<int:visit_id>/',
        save_medicine, name='save_medicine'),
    #
    path('add/prescription/for/patient/<int:patient_id>/visit/<int:visit_id>/',
        add_new, name='add_new'),
    #
    path('patient/<int:patient_id>/visit/<int:visit_id>/drug/<int:id>/', 
        edit_medicine, name='edit_medicine'),
    #
    path('patient/<int:patient>/visit/<int:visit>/delete/drug/<int:id>/', delete_medicine, name='delete_medicine'),
    path('table/medicine/', table_medicine, name='table_medicine'),
    
    #
    # path('prescription/visit/<int:visit_id>/', get_pdf, name='get_pdf'),
    
    # This is a good one for printing prescription
    path('print/visit/<int:visit_id>/', print_html, name='print_html'),
    #
    
]

apps/visits/urls.py
from django.urls import path  
from .views import *


app_name = 'visits'
urlpatterns = [
  
    # for visit
    path('create/visit/patient/<int:id>/', 
        pass_patient_id, name='pass_patient_id'),
    path('edit/visit/<int:id>/patient/<int:patient_id>/', 
        visits_patient_id, name='visits_patient_id'),
    
    # path('edit/visit/<int:id>/', visits.edit_visits, name='edit_visits'),
    path('table/list/all/visits/', table_visits, name='table_visits'),
    path('export/table/', export_table, name='export_table'),
   
]

metclinic/urls.py
# from os import name
from .utils import backup
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
import debug_toolbar

from .utils import talk_with_reg
from apps.home.views import frontpage

urlpatterns = [
    path('admin/', admin.site.urls),

    # Frontpage 
    path('', frontpage, name='frontpage'),

    path('backup/', backup, name='backup'),
    
    #
    path('lab/', include('apps.labs.urls', namespace='labs')),
    path('patientdata/', include('apps.patientdata.urls', namespace='patientdata')),
    path('pasthistory/', include('apps.pasthistory.urls', namespace='pasthistory')),
    path('presenthistory/', include('apps.presenthistory.urls', namespace='presenthistory')),

    path('revisitdrug/', include('apps.revisitdrug.urls', namespace='revisitdrug')),
    path('revisits/', include('apps.revisits.urls', namespace='revisits')),
    
    path('search/', include('apps.search.urls', namespace='search')),
    
    path('reports/', include('apps.reports.urls', namespace='reports')),
    path('visits/', include('apps.visits.urls', namespace='visits')),
    path('medicine/', include('apps.visitdrug.urls', namespace='visitdrug')),

    path('any/', talk_with_reg, name='talk_with_reg'),
    path('__debug__/', include(debug_toolbar.urls)),


    # the next two linesare for (DEBUG=False) to static works without any problem
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/revisits/models.py
from django.db import models
from django.urls import reverse
from django.utils.timezone import timezone
from datetime import date
from string import ascii_uppercase, digits
import random

from apps.patientdata.models import Patients
from apps.visits.models import Visits


# Create your models here.

class Revisits(models.Model):
    visitdate    = models.DateField(default=date.today, blank=True, null=True)
    complain     = models.TextField(blank=True, null=True)
    sign         = models.TextField(null=True, blank=True)
    diagnosis    = models.CharField(max_length=150, null=True, blank=True)
    intervention = models.CharField(max_length=150, null=True, blank=True)
    amount       = models.IntegerField(default=0, blank=True)
    patient      = models.ForeignKey(Patients, null=True, blank=True, on_delete=models.CASCADE)
    visit        = models.ForeignKey(Visits, null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "{}".format(self.id)

    def get_url(self):
        return reverse('revisitdata:save_revisit', 
                        kwargs={'patient':self.patient_id, 'visit':self.visit})



apps/revisits/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.db.models import Max
from django.db import connection, transaction
from django.contrib import messages
# from django.contrib.postgres.search import SearchVector

from apps.patientdata.models import Patients
from apps.visits.models import Visits
from apps.visitdrug.models import Medicine
from apps.revisitdrug.models import Remedicine 
from apps.presenthistory.models import PresentHistory
from apps.patientdata.tables import PatientsTable
from apps.visits.tables import VisitsTable

from .models import Revisits
from .forms import RevisitsForm
from .tables import RevisitsTable


# new save revisit 
def save_revisit(request, patient_id, visit_id): # Making save to new visits
    patient = Patients.objects.get(id=patient_id) # out put is the patient name
    patid = Patients.objects.values('id').filter(id=patient_id).first() # This is out put of without .first()=> <QuerySet [{'id': 36}]>
    var = patid['id']
    
    visit = Visits.objects.get(id=visit_id)
    # visitdate = Visits.objects.values('visitdate').filter(id=visit_id).first()
    # vis_date = visitdate['visitdate']
    visitid = Visits.objects.values('id').filter(id=visit_id).first()
    vis_id = visitid['id']

    match_present = PresentHistory.objects.filter(visit=visit_id).exists()
    present = PresentHistory.objects.values('id').filter(visit=visit_id).first()
    if not match_present:
        present = None #PresentHistory.objects.all()
        present_qs = None
    else:
        presentid = present['id']
        present_qs = PresentHistory.objects.get(id=presentid)

    match_medicine = Medicine.objects.filter(visit=visit_id).exists()
    match_revisit_medicine = Remedicine.objects.filter(visit=visit_id).exists()
    # if match_medicine:
    #     medicine = Medicine.objects.get(visit=visit_id)
    # else:
    #     medicine = None
    
    bound_form = RevisitsForm(data={
                'patient':patient, 
                'visit':visit,
                # 'visitdate':vis_date,
                })
    
    if request.method == 'POST':
        form = RevisitsForm(request.POST or None)
        if form.is_valid():
            save_form = form.save(commit=False)
            save_form.patient_id = patient_id
            save_form.visit_id = visit_id
            save_form.save()
            return redirect(reverse('revisits:view_revisit',  args=(visit_id, patient_id)))#kwargs={'visit':visit_id, 'patient':patient_id}))
    else:
        form = RevisitsForm()
    
    context = {
        'visit': visit,
        'present': match_present,
        'present_id': present_qs,
        'pat_id': var,
        'patient': patient, 
        'medicine': match_medicine,
        'remidicine': match_revisit_medicine,
        'save_revisits_form': form,
        'bound_form': bound_form,
    }
    return render(request, 'revisits/add_revisit.html', context)

#
def edit_revisit(request, patient_id, visit_id, id):
    query = Revisits.objects.get(id=id)  # out put Revisit ID
    qs = Revisits.objects.values('patient_id').filter(patient_id=patient_id).first() # {'patient_id': 2}
    # for get_url() to redirect to -save present history- form
    # test = Visits.objects.values('id', 'patient')\
    #                     .filter(id=id, patient=patient_id).first()  # {'id': 136, 'patient': 15}
    # print(qs, test)
    visit = Visits.objects.get(id=visit_id) # 
    
    patient = Patients.objects.get(id=patient_id) # Use it with get_absolute_url()
    patientid = qs['patient_id'] # out put is Patient ID
    
    match_present = PresentHistory.objects.filter(visit=visit_id).exists()
    if not match_present:
        present = None #PresentHistory.objects.all()
    else:
        present = PresentHistory.objects.get(visit=visit_id)

    bound_form = RevisitsForm(data={
                                    'patient':patient, 
                                    'visit':visit,
                                    # 'visitdate':vis_date,
                                    })

    form = RevisitsForm(request.POST or None, instance=query)
    if form.is_valid():
        # patid = request.POST.get('patient')
        # # print('patid : ' + str(patid))
        # match = Visits.objects.filter(patient_id=patid, id=visit_id).exists()
        # if match:
        save_form = form.save(commit=False)
        save_form.patient_id = patient_id
        save_form.visit_id = visit_id
        save_form.save()
        # print(patid)
        return redirect(reverse('revisits:edit_revisit', args=(query, patientid, visit_id)))  # ('/clinic/table/')
        #  HTTPResponseRedirect(reverse('patientdata:edit_patient', kwargs={'id': id}))
        # else:
        #     messages.success(request, 'The Patient Name Must Be : ' + \
        #     str(patient) + ', With Patient ID : ' + str(patient_id) + ' Not Ptient ID : ' + str(patid))

    context = {
        'patient': patient,
        'patient_id': patientid,
        'query': query,
        'present': match_present,
        'present_id': present,
        'visit': visit,
        'bound_form': bound_form,
        'edit_revisits_form': form,
    }
    return render(request, 'revisits/edit_revisit.html', context)

#
def table_revisit(request):
    qs = Revisits.objects.select_related('patient', 'visit')#.order_by('id')
    # ('-visits_visits.id') # the next lines are the result of this query ORM
    # qs = Revisits.objects.all().order_by('-id')
    print(qs.query)
    page_no = request.GET.get('pageno')
    if page_no == None or page_no == '' or int(page_no) == 0:
        table = RevisitsTable(qs, exclude='prn')
        table.paginate(page=request.GET.get("page", 1), per_page=10)
    else:
        table = RevisitsTable(qs, exclude='prn')
        table.paginate(page=request.GET.get("page", 1), per_page=page_no)

    # print(qs.query)
    context = {
        # 'qs_table': qs,
        'revisits_table': table,
    }
    return render(request, 'revisits/tables.html', context)

def view_revisit(request, visit_id, patient_id):
    visit = Visits.objects.get(id=visit_id)
    patient = Patients.objects.get(id= patient_id)
    qs = Revisits.objects.filter(visit=visit_id).order_by('-id')
    table = RevisitsTable(qs, exclude='patient, visit')
    table.paginate(page=request.GET.get("page", 1), per_page=10)

    context = {
        'visit': visit,
        'patient': patient,
        'view_revisits_table': table,
    }
    return render(request, 'revisits/tables.html', context)

def delete_revisit(request, id):
    del_revisit = Revisits.objects.get(id=id)
    del_revisit.delete()
    return redirect('revisits:table_revisit')



# def table_revisit(request):
#     # qs = Revisits.objects.select_related('patient').order_by('-id') # the next lines are the result of this query ORM
#     # qs = Visits.objects.all().order_by('-id')
#     qs = Revisits.objects.all().order_by('-id')
#     table = RevisitsTable(qs, exclude='addpresent')
#     table.paginate(page=request.GET.get("page", 1), per_page=10)
#     print(qs.query)
#     context = {
#         # 'qs_table': qs,
#         'revisits_table': table,
#     }
#     return render(request, 'revisitdata/tables.html', context)

apps/revisits/templates/revisits/add_revisit.html
{% extends 'index.html' %} {% load crispy_forms_tags %} 
{% load render_table from django_tables2 %} 
{% load static %}
<!--  -->

{% block content %}

 <h1 style="color: black;"><strong>Add Revisit for ({{patient}})</strong></h1>
 <hr>
 <div class="container">
    <a class="btn btn-outline-dark" href="{% url 'visits:pass_patient_id' pat_id %}" role="button" id="new-visit">
        Add New Visit
    </a>
    <a class="btn btn-outline-primary" href="{% url 'visits:visits_patient_id' visit.id patient.id %}" role="button" id="edit-patient">
        Edit Visit No. {{visit}}
    </a>
    <a class="btn btn-outline-primary" href="{{ patient.edit_patient_url}}" role="button" id="edit-patient">
        Edit Patient Data
    </a>
    <!--  -->
    {% if present %}
        <a class="btn btn-outline-primary" href="{% url 'presenthistory:edit_present_hist' patient.id visit.id present_id.id %}" role="button" id="present-history">
            Edit Present History
        </a>
    {% else %}
        <a class="btn btn-outline-danger" href="{% url 'presenthistory:save_present_hist' patient.id visit.id  %}" role="button" id="present-history">
            Add Present History
        </a>
    {% endif %}
    <!--  -->
    <!-- {% if medicine %}
    <a class="btn btn-info" href="{% url 'visitdrug:save_medicine' patient.id visit.id %}" role="button">
        Show Prescription
    </a> {% else %}

    <a class="btn btn-danger" href="{% url 'visitdrug:save_medicine' patient.id visit.id %}" role="button">
        Add Prescription
    </a> {% endif %} -->
    
    <!-- <a class="button is-primary float-right" href="{% url 'revisits:view_revisit' visit.id patient.id %}" role="button">
        All Revists for Visit No. {{visit}}
    </a> -->
    <!-- <a class="btn btn-primary" href="{{ query.edit_patient_url }}" role="button">
            Prescription function
        </a> -->
</div>
 <!-- <form class="form-inline mt-2 mt-md-0 float-right" method="GET" action="#">

     <input class="form-control mr-sm-2" type="text" name='vis' placeholder="Search Visits ..." value="{{request.GET.vis}}" aria-label="Search">
 
     <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
 </form> -->
 <hr>
 <form method="post">{% csrf_token %}
     <!--  -->
     <!-- {{ save_visits_form|crispy }} <br><br> -->
     <div class="float-left" style="width: 45%; height: 45%;" id="left-saverevis-div">
         <!-- {{save_revisits_form.visit.label_tag}} {{bound_form.visit}} <br>
         
         {{save_revisits_form.patient.label_tag}} {{bound_form.patient}} <br>  -->
         
         {{save_revisits_form.visitdate.label_tag}} {{save_revisits_form.visitdate}} <br>
         <!--  -->
         {{save_revisits_form.complain.label_tag}} {{save_revisits_form.complain}} <br>
         <!--  -->
         {{save_revisits_form.amount.label_tag}} {{save_revisits_form.amount}}
         <hr>
         <!-- <input type="button" value=""> -->
         <!-- <input type="submit" class="btn btn-outline-light" role="button" value="Save" id="vis-form-btn" /> -->
         <button type="submit" class="btn btn-dark" id="savepatform-btn">
             Save
         </button>

     </div>
     <div class="float-right" style="width:45%; height:45%;" id="right-saverevis-div">
         <!--  -->
         {{save_revisits_form.diagnosis.label_tag}} {{save_revisits_form.diagnosis}} <br>
         <!--  -->
         {{save_revisits_form.sign.label_tag}} {{save_revisits_form.sign}} <br>
         <!--  -->
         {{save_revisits_form.intervention.label_tag}} {{save_revisits_form.intervention}}
         <hr>
     </div>
 </form>

{% endblock %}

apps/revisits/templates/revisits/edit_revisit.html
{% extends 'index.html' %} {% load crispy_forms_tags %} 
{% load render_table from django_tables2 %} 
{% load static %}
<!--  -->

{% block content %}

<div >
    <h1 style="color: black;"><strong>Update Revisit for ({{patient}})</strong></h1>
</div>
<hr>
<!-- <div class="align-content-center float-left" style="background-color:transparent; width: 100%; height: 100%; margin: 10px; padding: 10px; border-style: outset; border-radius: 20px; border-color: #aab5af; box-shadow: 2px 2px 4px 4px grey;"> -->
    
<div class="container">
    <a class="btn btn-outline-dark" href="{% url 'visits:pass_patient_id' patient_id %}" role="button" id="new-visit">
        Add New Visit
    </a>
    <a class="btn btn-outline-dark" href="{% url 'revisits:save_revisit' patient.id visit.id %}" role="button" id="edit-patient">
        Add New Revisit
    </a>
    <a class="btn btn-outline-primary" href="{{ patient.get_absolute_url}}" role="button" id="edit-patient">
        Edit Patient Data
    </a>
    <a class="btn btn-outline-primary" href="{% url 'visits:visits_patient_id' visit.id patient.id %}" role="button" id="edit-patient">
        Edit Visit No. {{visit}}
    </a>
    <!--  -->
    {% if present %}
    <a class="btn btn-outline-primary" href="{% url 'presenthistory:edit_present_hist' patient.id visit.id present_id.id %}" role="button" id="present-history">
        Edit Present History
    </a>
    <!--  -->
    {% else %}
    <a class="btn btn-outline-danger" href="{% url 'presenthistory:save_present_hist' patient.id visit.id  %}" role="button" id="present-history">
        Add Present History
    </a>
    <!--  -->
    {% endif %}
    <!-- <a class="btn btn-secondary" href="#under construction" role="button">
        Prescription
    </a> -->
    
    <!-- <a class="btn btn-success float-right" href="{% url 'revisits:view_revisit' visit.id patient.id %}" role="button">
        All Revists for Visit No. {{visit}}
    </a> -->
</div>
    <!-- <a class="btn btn-primary" href="{{ query.get_absolute_url }}" role="button">
            Prescription function
        </a> -->
    <hr>
<!-- </div> -->
<!-- <br>
<br> -->

<!-- <div class="align-content-center float-right" style="background-color:transparent; width: 25%; height: 100%; margin: 10px; padding: 10px; border-style: outset; border-radius: 20px; border-color: #aab5af; box-shadow: 2px 2px 4px 4px grey;"> -->
    <!-- <form class="form-inline mt-2 mt-md-0 float-right" method="GET" action="{% url 'search:search_visit' %}">

        <input class="form-control mr-sm-2" type="text" name='vis' placeholder="Search Visits ..." value="{{request.GET.vis}}" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form> -->
    <!-- <hr> -->
<!-- </div> -->
<br>
<br>
<!-- <hr> -->
<form method="post">{% csrf_token %}
    <!--  -->
    <!-- {{ save_visits_form|crispy }} <br><br> -->
    <!-- <hr> -->
    <div class="float-left" style="width:45%; height:45%;" id="left-saverevis-div">
        <!-- {{edit_revisits_form.visit.label_tag}} {{bound_form.visit}} <br>
        {{edit_revisits_form.patient.label_tag}} {{bound_form.patient}} <br> -->
        {{edit_revisits_form.visitdate.label_tag}} {{edit_revisits_form.visitdate}} <br>
        
        {{edit_revisits_form.complain.label_tag}} {{edit_revisits_form.complain}} <br>
        
        {{edit_revisits_form.amount.label_tag}} {{edit_revisits_form.amount}}
        <hr>
        
        <button type="submit" class="btn btn-dark id="savepatform-btn">
            Update
        </button>

    </div>
    <div class="float-right" style="width:45%; height:45%;" id="right-saverevis-div">
        
        <!--  -->
        {{edit_revisits_form.diagnosis.label_tag}} {{edit_revisits_form.diagnosis}} <br>
        <!--  -->
        {{edit_revisits_form.sign.label_tag}} {{edit_revisits_form.sign}} <br>
        <!--  -->
        {{edit_revisits_form.intervention.label_tag}} {{edit_revisits_form.intervention}}
        <hr>
    </div>
</form>

  
{% endblock %}


apps/revisits/templates/revisits/tables.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load render_table from django_tables2 %} 

{% block content %}

<!-- <div class="align-content-center" style="background-color:transparent; width: 1300px; height: 900px; margin: 20px; padding: 10px; border-style: outset; border-radius: 20px; border-color: #aab5af; box-shadow: 2px 2px 4px 4px grey; display: grid;" id="save-visits-div"> -->
  
    <!--  -->
    {% if revisits_table %}
        <p class="float-left">
            <h1><strong>All Revisits Data</strong></h1>
        </p>
        <form class="form-inline mt-2 mt-md-0" method="GET" action="{% url 'revisits:table_revisit' %}">
        
            <input class="form-control mr-sm-2" type="number" name='pageno' placeholder="Edit pagination pages here.." value="{{request.GET.pageno}}" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>
                Search</button>
        
        </form>
        <br>
        <br>
        {% render_table revisits_table %}
        <!--  -->
    {% elif view_revisits_table %}
    <!-- <div class="align-content-center" style="background-color:white; height: 100%; width: 100%; margin: 30px;
        display: inline-block; position:relative; padding: 10px; border-style: outset; border-radius: 20px; 
        border-color: #aab5af; box-shadow: 2px 2px 4px 4px grey;" id="tables-div" name="mydiv"> -->
        <p class="float-left">
            <h1><strong>All Revisits For Visit No. ({{visit}})</strong></h1>
        </p>
        <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{% url 'revisits:view_revisit' visit.id patient.id %}">
            <input class="form-control mr-sm-2" type="text" name='pageno' placeholder="Edit pagination pages here..." value="{{request.GET.pageno}}" aria-label="Search">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
        </form>
        <!-- <a class="btn btn-secondary float-right" href="#" type="button">Button</a> -->
        <br><br>
        {% render_table view_revisits_table %}
    
    {% endif %}

<!-- </div> -->
  
{% endblock %}