apps/reports/urls.py
from django.urls import path

from .views import (
    calculate_income, calculate_day_income, print_html,
    calculate_month_income, calculate_year_income,
    # getpdf, get_pdf, print_pdf, 
    fast_print
)


app_name = 'reports'
urlpatterns = [
    path('income/year/<int:year>/', calculate_income, name='year_income'),
    # path('income/day/', calculate_income, name='calculate_day_income'),
    path('print/year/report/', print_html, name='print_html'),
    path('fast/print/', fast_print, name='fast_print'),
    # for test export to pdf
    # path('print/preview/export/to/pdf/', getpdf, name='getpdf'),
    # path('justin/export/to/pdf/', get_pdf, name='get_pdf'),
    # path('stack/export/pdf/', print_pdf, name='print_pdf'),
    
    path('income/day/', calculate_day_income, name='calculate_day_income'),
    path('income/month/', calculate_month_income, name='calculate_month_income'),
    path('income/year/', calculate_year_income, name='calculate_year_income'),
    
]






metclinic/urls.py
# from os import name
from .utils import backup
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
import debug_toolbar

from .utils import talk_with_reg
from apps.home.views import frontpage

urlpatterns = [
    path('admin/', admin.site.urls),

    # Frontpage 
    path('', frontpage, name='frontpage'),

    path('backup/', backup, name='backup'),
    
    #
    path('lab/', include('apps.labs.urls', namespace='labs')),
    path('patientdata/', include('apps.patientdata.urls', namespace='patientdata')),
    path('pasthistory/', include('apps.pasthistory.urls', namespace='pasthistory')),
    path('presenthistory/', include('apps.presenthistory.urls', namespace='presenthistory')),

    path('revisitdrug/', include('apps.revisitdrug.urls', namespace='revisitdrug')),
    path('revisits/', include('apps.revisits.urls', namespace='revisits')),
    
    path('search/', include('apps.search.urls', namespace='search')),
    
    path('reports/', include('apps.reports.urls', namespace='reports')),
    path('visits/', include('apps.visits.urls', namespace='visits')),
    path('medicine/', include('apps.visitdrug.urls', namespace='visitdrug')),

    path('any/', talk_with_reg, name='talk_with_reg'),
    path('__debug__/', include(debug_toolbar.urls)),


    # the next two linesare for (DEBUG=False) to static works without any problem
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/reports/models.py
from django.db import models

# Create your models here.

apps/reports/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.db.models import Q, Max
from django.db import connection, transaction
from django.contrib import messages
from datetime import datetime, date
# from django.contrib.postgres.search import SearchVector

from apps.patientdata.forms import PatientsForm
from apps.patientdata.models import Patients
from apps.visits.forms import VisitsForm
from apps.visits.models import Visits
from apps.patientdata.tables import PatientsTable
from apps.visits.tables import VisitsTable

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def calculate_day_income(request):
    today = date.today()#datetime.now()

    day_income = Visits.objects.filter(visitdate__year=today.year, 
                                        visitdate__month=today.month,
                                        visitdate__day=today.day)
    table = VisitsTable(day_income, exclude='addpresent')
    table.paginate(page=request.GET.get("page", 1), per_page=3)
    # print(day_income)
    search_name = request.GET.get('name')
    search_vis = request.GET.get('vis')
    search_date = request.GET.get('d')
    search_dia = request.GET.get('dia')
    if search_name == None and search_vis == None and search_date == None and search_dia== None: 
        table = VisitsTable(day_income, exclude='addpresent')
        table.paginate(page=request.GET.get("page", 1), per_page=10)
    elif ('vis' in request.GET) and request.GET['vis']:#search_vis != '':
        visit = Visits.objects.filter(Q(id=search_vis,
                                        visitdate__year=today.year, 
                                        visitdate__month=today.month, visitdate__day=today.day))
        table = VisitsTable(visit, exclude='addpresent')
        # table.paginate(page=request.GET.get("page", 1), per_page=5)
    elif ('d' in request.GET) and request.GET['d']: 
        result_date = Visits.objects.filter(Q(visitdate=search_date))
        table = VisitsTable(result_date, exclude='addpresent')
        table.paginate(page=request.GET.get("page", 1), per_page=10)
    elif ('name' in request.GET) and request.GET['name'].strip():#
        patient = Visits.objects.filter(Q(patient__name__icontains=search_name,
                                        visitdate__year=today.year, visitdate__month=today.month, visitdate__day=today.day)) # note HERE '__name__icontains' it's important to get related field "patient"(string not id) 
        table = VisitsTable(patient, exclude='addpresent')
        table.paginate(page=request.GET.get("page", 1), per_page=10)
    elif ('dia' in request.GET) and request.GET['dia']: 
        result_dia = Visits.objects.filter(Q(diagnosis=search_dia, visitdate__year=today.year, visitdate__month=today.month, visitdate__day=today.day))
        table = VisitsTable(result_dia, exclude='addpresent')
        table.paginate(page=request.GET.get("page", 1), per_page=10)
    # elif search_vis == "" or int(search_vis) == 0: 
    #     table = VisitsTable(month_income, exclude='addpresent')
    #     table.paginate(page=request.GET.get("page", 1), per_page=10)
    else:
        table = VisitsTable(day_income, exclude='addpresent')
        table.paginate(page=request.GET.get("page", 1), per_page=10)
    
    context = {
            'day_table': table,
    }
    return render(request, 'reports/day_table.html', context)


def calculate_month_income(request):
    today = date.today()       # datetime.now()
    month_income = Visits.objects.filter(visitdate__year=today.year, visitdate__month=today.month)
    table = VisitsTable(month_income, exclude='addpresent')
    table.paginate(page=request.GET.get("page", 1), per_page=10)
    
    income = Visits.objects.values('visitdate').filter(visitdate__year=2020, visitdate__month=12)
    print(income, income[0], income[0]['visitdate'], income[0]['visitdate'].month)

    search_name = request.GET.get('name')
    search_vis = request.GET.get('vis')
    search_dia = request.GET.get('dia')
    search_month = request.GET.get('month')
    if search_name == None and search_vis == None and search_dia == None and search_dia == None and search_month == None: 
        table = VisitsTable(month_income, exclude='addpresent')
        table.paginate(page=request.GET.get("page", 1), per_page=10)
    elif ('vis' in request.GET) and request.GET['vis']:
        visit = Visits.objects.filter(Q(id=search_vis, visitdate__year=today.year, visitdate__month=today.month))
        table = VisitsTable(visit, exclude='addpresent')
    elif ('month' in request.GET) and request.GET['month']:
        result_month = Visits.objects.filter(Q(visitdate__year=today.year, visitdate__month=search_month))
        table = VisitsTable(result_month, exclude='addpresent')
        table.paginate(page=request.GET.get("page", 1), per_page=5)
    elif ('dia' in request.GET) and request.GET['dia']: 
        result_dia = Visits.objects.filter(Q(diagnosis__icontains=search_dia, visitdate__year=today.year, visitdate__month=today.month))
        table = VisitsTable(result_dia, exclude='addpresent')
        table.paginate(page=request.GET.get("page", 1), per_page=10)
    elif ('name' in request.GET) and request.GET['name'].strip():#
        patient = Visits.objects.filter(Q(patient__name__icontains=search_name,
                                        visitdate__year=today.year, visitdate__month=today.month)) # note HERE '__name__icontains' it's important to get related field "patient"(string not id) 
        table = VisitsTable(patient, exclude='addpresent')
        table.paginate(page=request.GET.get("page", 1), per_page=10)
    else:
        table = VisitsTable(month_income, exclude='addpresent')
        table.paginate(page=request.GET.get("page", 1), per_page=10)
    
    context = {
        'month_table': table,
    }
    return render(request, 'reports/month_table.html', context)


def calculate_year_income(request):
    today = date.today()#datetime.now()
    # income = Visits.objects.all()
    # table = VisitsTable(income)
    # table.paginate(page=request.GET.get('page', 1), per_page=10)

    year_income = Visits.objects.filter(visitdate__year=today.year).order_by('-id')
    year_table = VisitsTable(year_income, exclude='addpresent')
    year_table.paginate(page=request.GET.get("page", 1), per_page=10)
    
    print_table = VisitsTable(year_income, exclude='addpresent, addlab, addrevis')
    print_table.paginate(page=request.GET.get("page", 1), per_page=10)

    context = {
        'year_table': year_table,
        'print_table': print_table,
    }
    return render(request, 'reports/year_table.html', context)



def calculate_income(request, year):
    today = date.today()#datetime.now()
    day = today.day
    month = today.month
    year = today.year
    # income = Visits.objects.all()
    # table = VisitsTable(income)
    # table.paginate(page=request.GET.get('page', 1), per_page=10)
    # if day is not None and month is not None and year is not None:
    #     day_income = Visits.objects.filter(visitdate__year=today.year, visitdate__month=today.month, visitdate__day=today.day)
    #     table = VisitsTable(day_income)
    #     table.paginate(page=request.GET.get("page", 1), per_page=2)
    #     return redirect(reverse('clinic:day_income', args=(today.day, today.month, today.year)))
    # elif month is not None and year is not None:
    #     month_income = Visits.objects.filter(visitdate__year=today.year, visitdate__month=today.month)
    #     table = VisitsTable(month_income)
    #     table.paginate(page=request.GET.get("page", 1), per_page=3)
    #     return redirect(reverse('clinic:month_income', args=(today.month, today.year)))
    # if year != None:
    cal_year = Visits.objects.values('visitdate').filter(visitdate__year=year).first()
    year_value = cal_year['visitdate']
    # print(cal_year, year_value)
    year_income = Visits.objects.filter(visitdate__year=today.year).order_by('-id')
    table = VisitsTable(year_income, exclude='addpresent')
    table.paginate(page=request.GET.get("page", 1), per_page=5)
    return redirect('/clinic/income/year/'+ str(year_value.year) +'/')
    
    context = {
        'income_table': table,
    }
    return render(request, 'tables.html', context)


# This method to print prescription
def print_html(request):
    today = date.today()#datetime.now()
    qs = Visits.objects.filter(visitdate__year=today.year).order_by('-id')
    table = VisitsTable(qs, exclude='addpresent, addlab, addrevis, diagnosis,')
    # table.paginate(page=request.GET.get("page", 1), per_page=5)
    
    page_no = request.GET.get('pageno')
    if page_no == None or page_no == '' or int(page_no) == 0:
        table = VisitsTable(qs, exclude='addpresent, addlab, addrevis, diagnosis,')
        table.paginate(page=request.GET.get("page", 1), per_page=10)
        # paginator = Paginator(qs, 10) 
        # page = request.GET.get('page')
        # try:
        #     qs_page = paginator.page(page)
        # except PageNotAnInteger:
        #     # If page is not an integer deliver the first page
        #     qs_page = paginator.page(1)
        # except EmptyPage:
        #     # If page is out of range deliver last page of results
        #     qs_page = paginator.page(paginator.num_pages)
        # qs = Visits.objects.filter(visitdate__year=today.year).order_by('-id')
        
    elif page_no != None or page_no != '' or int(page_no) != 0:
        table = VisitsTable(qs, exclude='addpresent, addlab, addrevis, diagnosis,')
        table.paginate(page=request.GET.get("page", 1), per_page=page_no)
        # paginator = Paginator(qs, page_no) 
        # page = request.GET.get('page')
        # try:

apps/reports/templates/reports/day_table.html
{% extends 'index.html' %} 
<!-- {% load static %}  -->
{% load render_table from django_tables2 %} 

<!--  -->
{% url 'reports:calculate_day_income' as day_url %}
<!--  -->
{% url 'reports:calculate_month_income' as month_url %}
<!--  -->
{% url 'reports:calculate_year_income' as year_url %}
<!--  -->

{% block content %}
        
    <p class="float-left">
        <h1><strong>Daily Report</strong></h1>
    </p>
    <div class="container">
        <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{{ day_url }}">

            <input class="form-control mr-sm-2" type="text" name='name' placeholder="Patient Name ..." value="{{request.GET.name}}" aria-label="Search">
        
            <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
            
        </form> &nbsp;&nbsp;

        <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{{month_url}}">

            <input class="form-control mr-sm-2" type="number" name='vis' placeholder="Visit ID ..." value="{{request.GET.vis}}" aria-label="Search">
            
            <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
            
        </form>&nbsp;&nbsp;

        <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{{month_url}}">

            <input class="form-control mr-sm-2" type="date" name='d' placeholder="Specific Date..." value="{{request.GET.d}}" aria-label="Search">
            
            <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
            
        </form>

        <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{{day_url}}">

            <input class="form-control mr-sm-2" type="text" name='dia' placeholder="Diagnosis ..." value="{{request.GET.dia}}" aria-label="Search">
            
            <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
            
        </form>
    </div>

    <br><br>
    {% render_table day_table %}

{% endblock %}


{% block scripts %}

    <!-- Write javascript code Here -->
    <script type="text/javascript">    
        $(document).ready(function() {
            
        })
    </script>
    
    <script>
        var editPasthist = new Vue ({
            // el: '#edit-pasthist',
            // delimiters: ['[[', ']]'],
            // data: {
        //         title: "Edit Past History",
        //         message: 'Code with amr',
        //         showDialog: false,
        //         category_id: 0,
            // },
            methods: {
                
            }
        });
        // new instance of Vue.js
        var savePasthist = new Vue({
            // el: '',
            // delimiters: ['[[', ']]'],
            // data: {
            //     title: "Add Past History",
            // }
        });
        
    </script>

{% endblock  %}

apps/reports/templates/reports/month_table.html
{% extends 'index.html' %} 
<!-- {% load static %}  -->
{% load render_table from django_tables2 %} 
<!-- {% load crispy_forms_tags %}  -->
<!-- {% load export_url from django_tables2 %} -->

<!--  -->
{% url 'reports:calculate_day_income' as day_url %}
<!--  -->
{% url 'reports:calculate_month_income' as month_url %}
<!--  -->
{% url 'reports:calculate_year_income' as year_url %}
<!--  -->


{% block content %}

        <p class="float-left">
            <h1><strong>Monthly Report</strong></h1>
        </p>
        <div class="container">
            <!-- <a class="btn btn-secondary float-right" href="#" type="button">Button</a> -->
            <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{{month_url}}">

                <input class="form-control mr-sm-2" type="text" name='name' placeholder="Patient Name ..." value="{{request.GET.name}}" aria-label="Search">
                
                <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
                
            </form> &nbsp;&nbsp;

            <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{{month_url}}">

                <input class="form-control mr-sm-2" type="number" name='vis' placeholder="Visit ID ..." value="{{request.GET.vis}}" aria-label="Search">
                
                <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
                
            </form>&nbsp;&nbsp;

            <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{{month_url}}">

                <input class="form-control mr-sm-2" type="text" name='dia' placeholder="Diagnosis ..." value="{{request.GET.dia}}" aria-label="Search">
                
                <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
                
            </form>

            <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{{month_url}}">

                <input class="form-control mr-sm-2" type="number" name='month' placeholder="Search Month ..." value="{{request.GET.month}}" aria-label="Search">
                
                <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
                
            </form>

        </div>
        
        <br><br>
        {% render_table month_table %}  

{% endblock %}



{% block scripts %}

    <!-- Write javascript code Here -->
    <script type="text/javascript">    
        $(document).ready(function() {
            
        })
    </script>
    
    <script>
        var editPasthist = new Vue ({
            // el: '#edit-pasthist',
            // delimiters: ['[[', ']]'],
            // data: {
        //         title: "Edit Past History",
        //         message: 'Code with amr',
        //         showDialog: false,
        //         category_id: 0,
            // },
            methods: {
                
            }
        });
        // new instance of Vue.js
        var savePasthist = new Vue({
            // el: '',
            // delimiters: ['[[', ']]'],
            // data: {
            //     title: "Add Past History",
            // }
        });
        
    </script>

{% endblock  %}

apps/reports/templates/reports/print.html
{% extends 'index.html' %}
{% load static %} 

{% load render_table from django_tables2 %} 

{% load querystring from django_tables2 %} 


{% block content %}

        <br>
        <div class="container">
                <a type="button" class="btn btn-outline-primary" href="{% url 'reports:calculate_year_income' %}">
                    Back To Year Report
                </a>
                <button class="btn btn-outline-primary" id="print" onclick="printData()">
                <!-- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -->
                Print 
                <!-- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -->
                </button>

        </div>
        <hr>

        <div>
            <form class="form-inline mt-2 mt-md-0" method="GET" action="{% url 'reports:print_html' %}">

                <input class="form-control mr-sm-2" type="number" name='pageno' placeholder="Edit pagination pages here.." value="{{request.GET.pageno}}" aria-label="Search"> <br>
            
                <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
                
            </form>
        </div>


        <div class="align-content-center" style="margin: 20px; padding: 10px;" id="pdata">
        <!-- <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;R\
        </h4> -->
        
        
            <!-- <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="table-wrapper">
                            <table class="fl-table" id="table"> 
                                <thead>
                                    <tr>
                                        <th>Visit ID <hr></th> 
                                        <th>Patient Name <hr></th> 
                                        <th>Visit Date <hr></th> 
                                        <th>Amount <hr></th>
                                    </tr>
                                </thead>
                                {% for cl in qs_page %}
                                    <tbody>
                                        <tr>
                                            <td>{{cl.id}} <br><hr></td> 
                                            <td>{{cl.patient}} <br><hr></td>
                                            <td>{{cl.visitdate}} <br><hr></td>
                                            <td>{{cl.amount}} <br><hr></td> 
                                            
                                        </tr>
                                    </tbody>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div> -->

        <!-- table -->
        <div class="container" id='div-table' style="width: 100%;height: 100%;">
            {% render_table visit_table %}
        </div>


        {% include "home/pagination.html" with page=qs_page %}

    <!-- </body>
</html> -->
{% endblock %}



{% block scripts %}

<script type="text/javascript">
    // function printData() {
    //     // var spanToPrint = document.getElementById("p");
    //     var divPrint = document.getElementById("pdata");
    //     var divToPrint = document.getElementById("div-table");
    //     newWin = window.open("");
    //     // newWin.document.write(spanToPrint.innerHTML + divToPrint.outerHTML);
    //     newWin.document.write(divPrint.outerHTML + divToPrint.outerHTML);
    //     newWin.print();
    //     newWin.close();
    // } // + imgToPrint.innerHTML 
    function printData() {
    var divToPrint = document.getElementById('pdata');
    var htmlToPrint = '' +
        '<style type="text/css">' +
        'table th, table td {' +
        'border:1px solid #000;' +
        'padding:0.5em;' +
        'width:100%;' +
        'white-space:nowrap;' + // this line to make the cells flixable
        '}' +
        'p {' +
        'text-align: right' +
        'margin-bottom:0;' +
        'padding:0;' +
        'line-height:12px;' +
        'font-size:10px;' +
        '}' +
        '@media print {' +
        'nav { visibility: hidden; }' + // for remove pagination from    
        // printing
        '}' +
        '</style>';
    htmlToPrint += divToPrint.outerHTML;
    newWin = window.open("");
    newWin.document.write(htmlToPrint);
    newWin.print();
    newWin.close();
}

</script>
{% endblock  %}
    

apps/reports/templates/reports/year_table.html
{% extends 'index.html' %} 
<!-- {% load static %}  -->
{% load render_table from django_tables2 %} 
<!-- {% load crispy_forms_tags %}  -->
<!-- {% load export_url from django_tables2 %} -->


{% block content %}
    <div>
        <p class="float-left">
            <h1><strong>Yearly Report</strong></h1>
        </p>
        <a type="button" class="btn btn-outline-primary" href="{% url 'reports:print_html' %}">
            Print Preview
        </a>
        <button class="btn btn-outline-success" id="print" onclick="printData()">
            Print 
        </button>
        <!-- <a class="btn btn-outline-success" href="{% url 'reports:fast_print' %}">
            Fast Print 
        </a> -->
    </div>
    <br><br>
    <div class="container">
        {% render_table year_table %}
    </div>
    <div id="pdata" hidden>
        {% render_table print_table %}
    </div>
        

{% endblock %}



{% block scripts %}

<script type="text/javascript">

    function printData() {
    var divToPrint = document.getElementById('pdata');
    var htmlToPrint = '' +
        '<style type="text/css">' +
        'table th, table td {' +
        'border:1px solid #000;' +
        'padding:0.5em;' +
        'width:100%;' +
        'white-space:nowrap;' + // this line to make the cells flixable
        '}' +
        'p {' +
        'text-align: right' +
        'margin-bottom:0;' +
        'padding:0;' +
        'line-height:12px;' +
        'font-size:10px;' +
        '}' +
        '#pdata {display: block;}' +
        '@media print {' +
        'nav { visibility: hidden; }' + // for remove pagination from    
        // printing
        '}' +
        '</style>';
    htmlToPrint += divToPrint.outerHTML;
    newWin = window.open("");
    newWin.document.write(htmlToPrint);
    newWin.print();
    newWin.close();
}

</script>
{% endblock  %}
