apps/labs/urls.py
from django.urls import path
from .views import (
                    # add_lab_followup, edit_lab_followup,lab_followup_table,
                    add_lab_visit, edit_lab_visit,lab_visit_table,
                    delete_lab_visit)

from .prescription import print_html

app_name = 'labs'
urlpatterns = [
    path('add/visit/lab/for/patient/<int:patient_id>/visit/<int:visit_id>/', 
        add_lab_visit, name='add_lab_visit'),
    path('edit/visit/lab/<int:lab_id>/patient/<int:patient_id>/visit/<int:visit_id>/',
        edit_lab_visit, name='edit_lab_visit'),
    path('add/visits/lab/table/',
        lab_visit_table, name='lab_visit_table'),
    path('delete/visit/lab/<int:lab_id>/patient/<int:patient_id>/visit/<int:visit_id>/',
        delete_lab_visit, name='delete_lab_visit'),

    # path('add/lab/for/patient/<int:patient_id>/followup/visit/<int:followup_id>/', 
    #     add_lab_followup, name='add_lab_followup'),
    # path('edit/lab/<int:lab_id>/patient/<int:patient_id>/followup/visit/<int:followup_id>/',
    #     edit_lab_followup, name='edit_lab_followup'),
    
    # path('table/for/add/followup/visit/', 
    #     delete_lab_visit, name='delete_lab_visit'),

    path('prescription/analysis/for/visit/<int:visit_id>/',
        print_html, name='print_html'),
    
]

apps/patientdata/urls.py
from django.urls import path  # defs
# from clinic.views.home import homepage
from .views import (save_patient, edit_patient, table_patient)
from .operations import save_operation, edit_operation, operation_table
# from clinic.views import visits, medicine, prescription
# from clinic.views.search import search_patient, search_visit, search_date, search_only
# from clinic.views.calculations import (calculate_income, calculate_day_income, 
#                                         calculate_month_income, calculate_year_income)

app_name = 'patientdata'
urlpatterns = [

    # for patient
    path('create/patient/', save_patient, name='save_patient'),
    path('edit/patient/<int:id>/', edit_patient, name='edit_patient'),
    path('table/patients/', table_patient, name='table_patient'),
    # path('patient/details/by/barcode/<str:barcode>/', patient_details, name='patient_details'),
    
    # for operations
    path('add/operation/details/<int:patient_id>/', save_operation, name='save_operation'),
    path('add/operation/details/for/patient/<int:patient_id>/id/<int:id>/', edit_operation, name='edit_operation'),
    path('operation/table/', operation_table, name='operation_table'),
    
    # path('edit/visit/<int:id>/', visits.edit_visits, name='edit_visits'),
    # path('table/visits/', visits.table_visits, name='table_visits'),
    # path('export/table/', visits.export_table, name='export_table'),

    #
    # path('drug/patient/<int:patient_id>/visit/<int:visit_id>/',
    #     medicine.save_medicine, name='save_medicine'),
    #
    # path('add/prescription/patient/<int:patient_id>/visit/<int:visit_id>/',
    #     medicine.add_new, name='add_new'),
    #
    # path('patient/<int:patient_id>/visit/<int:visit_id>/drug/<int:id>/', 
    #     medicine.edit_medicine, name='edit_medicine'),
    
    #
    # path('patient/<int:patient>/visit/<int:visit>/delete/drug/<int:id>/', medicine.delete_medicine, name='delete_medicine'),
    # path('table/medicine/', medicine.table_medicine, name='table_medicine'),
    
    #
    # path('search/patient/', search_patient, name='search_patient'),
    # path('search/visit/', search_visit, name='search_visit'),
    # path('search/date/', search_date, name='search_date'),
    # path('search/only/date/', search_only, name='search_only'),

    #
    # path('income/day/<int:day>/<int:month>/<int:year>/', calculate_income, name='day_income'),
    # path('income/month/<int:day>/<int:month>/<int:year>/', calculate_income, name='month_income'),
    # path('income/year/<int:year>/', calculate_income, name='year_income'),
    # # path('income/day/', calculate_income, name='calculate_day_income'),
    # # path('income/month/', calculate_income, name='calculate_month_income'),
    # path('income/day/', calculate_day_income, name='calculate_day_income'),
    # path('income/month/', calculate_month_income, name='calculate_month_income'),
    # path('income/year/', calculate_year_income, name='calculate_year_income'),
    
    # #
    # path('prescription/visit/<int:visit_id>/', prescription.get_pdf, name='get_pdf'),
    # # This is a good one for printing prescription
    # path('print/visit/<int:visit_id>/', prescription.print_html, name='print_html'),
    # #
    # path('pdf/', prescription.some_view, name='some_view'),

]   

apps/visitdrug/urls.py
from django.urls import path
from .views import *
from .prescription import *
app_name= "visitdrug"

urlpatterns = [
    #
    path('prescription/for/patient/<int:patient_id>/visit/<int:visit_id>/',
        save_medicine, name='save_medicine'),
    #
    path('add/prescription/for/patient/<int:patient_id>/visit/<int:visit_id>/',
        add_new, name='add_new'),
    #
    path('patient/<int:patient_id>/visit/<int:visit_id>/drug/<int:id>/', 
        edit_medicine, name='edit_medicine'),
    #
    path('patient/<int:patient>/visit/<int:visit>/delete/drug/<int:id>/', delete_medicine, name='delete_medicine'),
    path('table/medicine/', table_medicine, name='table_medicine'),
    
    #
    # path('prescription/visit/<int:visit_id>/', get_pdf, name='get_pdf'),
    
    # This is a good one for printing prescription
    path('print/visit/<int:visit_id>/', print_html, name='print_html'),
    #
    
]

apps/visits/urls.py
from django.urls import path  
from .views import *


app_name = 'visits'
urlpatterns = [
  
    # for visit
    path('create/visit/patient/<int:id>/', 
        pass_patient_id, name='pass_patient_id'),
    path('edit/visit/<int:id>/patient/<int:patient_id>/', 
        visits_patient_id, name='visits_patient_id'),
    
    # path('edit/visit/<int:id>/', visits.edit_visits, name='edit_visits'),
    path('table/list/all/visits/', table_visits, name='table_visits'),
    path('export/table/', export_table, name='export_table'),
   
]

metclinic/urls.py
# from os import name
from .utils import backup
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
import debug_toolbar

from .utils import talk_with_reg
from apps.home.views import frontpage

urlpatterns = [
    path('admin/', admin.site.urls),

    # Frontpage 
    path('', frontpage, name='frontpage'),

    path('backup/', backup, name='backup'),
    
    #
    path('lab/', include('apps.labs.urls', namespace='labs')),
    path('patientdata/', include('apps.patientdata.urls', namespace='patientdata')),
    path('pasthistory/', include('apps.pasthistory.urls', namespace='pasthistory')),
    path('presenthistory/', include('apps.presenthistory.urls', namespace='presenthistory')),

    path('revisitdrug/', include('apps.revisitdrug.urls', namespace='revisitdrug')),
    path('revisits/', include('apps.revisits.urls', namespace='revisits')),
    
    path('search/', include('apps.search.urls', namespace='search')),
    
    path('reports/', include('apps.reports.urls', namespace='reports')),
    path('visits/', include('apps.visits.urls', namespace='visits')),
    path('medicine/', include('apps.visitdrug.urls', namespace='visitdrug')),

    path('any/', talk_with_reg, name='talk_with_reg'),
    path('__debug__/', include(debug_toolbar.urls)),


    # the next two linesare for (DEBUG=False) to static works without any problem
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/labs/forms.py
from django import forms
# from django.forms import ModelForm
from .models import LabVisit, LabFollowup
from django.utils.timezone import now
from datetime import date
# from .tables import MedicineTable
from apps.patientdata.models import Patients
from apps.visits.models import Visits

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _



class LabVisitForm(forms.ModelForm):
    name = forms.CharField(error_messages={'required':"This is required, Please fill this field ..."},
                            label='Analysis Name',
                            widget=forms.TextInput(
                                attrs={
                                    'class': 'form-control',
                                    'id': 'name',
                                #    'lang': 'arabic',
                                    # 'placeholder':'Type Your Drug ...',
                            }))

    result = forms.CharField(required=False, 
                            label='Result',
                            widget=forms.TextInput(
                                attrs={
                                    'class': 'form-control',
                                    # 'placeholder':'Type Your Plan ...',
                            }))
    image = forms.ImageField(required=False, 
                            label='Image',
                            widget=forms.ClearableFileInput(
                                attrs={
                                    'class': 'form-control',     
                            }))
    file = forms.FileField(required=False, 
                            label='File',
                            widget=forms.ClearableFileInput(
                                attrs={
                                    'class': 'form-control',     
                            }))
    resdate = forms.DateField(required=False,
                            label='Result Date',
                            widget=forms.TextInput(
                                attrs={
                                   'class': 'form-control',
                                   'type': 'date',
                                    'value': date.today(),
                                #    'placeholder': 'Type Your Plan ...',
                                # 'readonly':
                               }))
    
    class Meta:
        model = LabVisit
        fields = ('name', 'result', 'resdate', 'image', 'file')



class LabFollowupForm(forms.ModelForm):
    name = forms.CharField(error_messages={'required':"This is required, Please fill this field ..."},
                            label='Analysis Name',
                            widget=forms.TextInput(
                                attrs={
                                    'class': 'form-control',
                                    'id': 'name',
                                #    'lang': 'arabic',
                                    # 'placeholder':'Type Your Drug ...',
                            }))

    result = forms.CharField(required=False, 
                            label='Result',
                            widget=forms.TextInput(
                                attrs={
                                    'class': 'form-control',
                                    # 'placeholder':'Type Your Plan ...',
                            }))

    resdate = forms.DateField(required=True,
                            label='Result Date',
                            widget=forms.TextInput(
                                attrs={
                                   'class': 'form-control',
                                   'value': date.today(),
                                #    'lang': 'arabisk',
                                #    'placeholder': 'Type Your Plan ...',
                                # 'readonly':
                               }))
    
    class Meta:
        model = LabFollowup
        fields = ('name', 'result', 'resdate', )

apps/labs/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
from datetime import date

from .forms import LabVisitForm, LabFollowupForm
from .models import LabVisit, LabFollowup
from .tables import LabVisitTable

from apps.patientdata.models import Patients
from apps.visits.models import Visits
from apps.visits.tables import VisitsTable


import sysconfig
sysconfig.get_paths()['stdlib'] + 'mypackage'
from mypackage.myfile import * 

# Create your views here.

@auth_required
def add_lab_visit(request, patient_id, visit_id, *args, **kwargs):
    '''  '''
    patient = Patients.objects.get(id=patient_id)
    visit = Visits.objects.values('visitdate').filter(id=visit_id).first()
    visdate = visit['visitdate']
    
    # name = kwargs.get('patient')
    # print('name= ', name)
    match_lab = LabVisit.objects.filter(visit=visit_id,
                                        patient=patient_id).exists()

    if request.method == 'POST':
        form = LabVisitForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            lab_form = form.save(commit=False)
            lab_form.visit_id = visit_id
            lab_form.patient_id = patient_id
            lab_form.resdate = date.today()
            lab_form.save()
            messages.success(request, 'Saving analysis done ...')
            return redirect(reverse('labs:add_lab_visit', args=(patient_id, visit_id)))
    else:
        form = LabVisitForm()

    qs = LabVisit.objects.filter(visit=visit_id).order_by('-id')
    table = LabVisitTable(qs, exclude='id, visit, patient, addlab, result, resdate')
    table.paginate(page=request.GET.get("page", 1), per_page=10)

    context = {
        'visit': visit,
        'patient': patient,
        'lab_form': form,
        'patid': patient_id,
        'visid': visit_id,
        'lab_table': table,
        'vis_date': visdate,
        'match_lab': match_lab,
    }

    return render(request, 'labs/add_lab_visit.html', context)


def add_lab_followup(request, patient_id, followup_id):
    '''  '''
    if request.method == 'POST':
        form = LabFollowupForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            lab_form = form.save(commit=False)
            lab_form.followup = followup_id
            lab_form.patient = patient_id

            lab_form.save()
    else:
        form = LabFollowupForm()
    context = {
        'form': form,
    }

    return render(request, 'labs/add_lab_followup.html', context)


def edit_lab_visit(request, lab_id, patient_id, visit_id):
    '''  '''
    visit = Visits.objects.values('visitdate').filter(id=visit_id).first()
    visdate = visit['visitdate']

    match = LabVisit.objects.filter(id=lab_id).exists()
    if match:
        lab = LabVisit.objects.get(id=lab_id)
        form = LabVisitForm(request.POST or None, request.FILES or None, instance=lab)
    else:
        return redirect(reverse('labs:add_lab_visit', args=(patient_id, visit_id)))

    if form.is_valid():
        lab_form = form.save(commit=False)
        lab_form.visit_id = visit_id
        lab_form.patient_id = patient_id
        lab_form.save()
        messages.success(request, 'Saving changes done ...')
        return redirect(reverse('labs:edit_lab_visit', args=(lab_id, patient_id, visit_id)))

    qs = LabVisit.objects.filter(visit=visit_id).order_by('-id')
    table = LabVisitTable(qs, exclude='id, visit, patient, addlab')
    table.paginate(page=request.GET.get("page", 1), per_page=10)

    context = {
        'lab_form': form,
        'patid': patient_id,
        'visid': visit_id,
        'lab_id': lab_id,
        'lab_table': table,
        'lab': lab,
        'vis_date': visdate,        
    }

    return render(request, 'labs/edit_lab_visit.html', context)


def edit_lab_followup(request, lab_id, patient_id, followup_id):
    '''  '''
    qs = LabFollowup.objects.get(id=lab_id)
    form = LabVisitForm(request.POST or None, request.FILES or None, instance=qs)
    context = {

    }

    return render(request, 'labs/edit_lab_followup.html', context)


def lab_visit_table(request):
    '''  '''
    var = Visits.objects.all().order_by('-id')
    # var = PastHistory.objects.values('patient', 'histdate', 'pasthist').distinct()
    # var = PastHistory.objects.select_related('patient').distinct().order_by('-id')
    page_no = request.GET.get('pageno')
    if page_no == None or page_no == '' or int(page_no) == 0:
        table = VisitsTable(var, exclude='diagnosis, addpresent, addrevis')
        table.paginate(page=request.GET.get("page", 1), per_page=25)
    else:
        table = VisitsTable(var, exclude='diagnosis, addpresent, addrevis')
        table.paginate(page=request.GET.get("page", 1), per_page=page_no)
    
    context = {
        'lab_visit_table':table,
    }

    return render(request, 'labs/lab_visit_table.html', context)


def lab_followup_table(request):
    '''  '''
    context = {

    }

    return render(request, 'labs/tables.html', context)


def delete_lab_visit(request, lab_id, patient_id, visit_id):
    '''  '''
    lab_visit = LabVisit.objects.get(id=lab_id)
    lab_visit.delete()
    return redirect(reverse('labs:add_lab_visit', args=(patient_id, visit_id)))


def delete_lab_followup(request):
    '''  '''
    return redirect('/')

apps/labs/templates/labs/add_lab_visit.html
{% extends 'index.html' %} {% load crispy_forms_tags %} {% load render_table from django_tables2 %} {% load widget_tweaks %} {% load static %}
<!--  -->
{% block content %}
<div class="container" id="add-drug">

    {% if match_lab %} {% else %}
    <!-- for empty prescription -->
    <div class="alert {{ message.tags }} alert-dismissible fade show" style="background-color: lightpink; width: 98%; height: 100%; margin: 10px; padding: 15px;" role="alert">
        <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}>
            Please add analysis to this prescription
            <button type="button" class="close" data-dismiss="alert" aria-label="Close" style="color: black; margin: 5px; padding: 5px;">
                <span aria-hidden="true">&times;</span>
            </button>
        </li>
    </div>
    {% endif %}
    <br>

    <div class="float-left">
        <h1 style="color: black;">
            <strong>
                Add Lab Prescription for ({{patient}})
            </strong>
        </h1>
        <!-- <input class="float-right" type="text" name="pages" id="pages"> -->
        <p>
            <h3 style="color: black;">Visit Date : {{ vis_date }}</h3>
        </p>
        <br>
        <!-- <br><br><br> -->
    </div>

    <div class="container float-right" style="width: 100%; height: 100%;">
        <!-- <input type="text" value="{{vis_date}}" name="vis-date" id="vis-date"> -->
        <!-- <a class="btn btn-outline-dark" href="{% url 'visitdrug:save_medicine' patid visid %}" role="button">
            Add New Prescription
        </a> -->
        <a class="btn btn-outline-dark" href="{% url 'visits:pass_patient_id' patid %}" role="button" id="new-visit">
            New Visit
        </a>
        <a class="btn btn-outline-primary" href="{% url 'patientdata:edit_patient' patid %}" role="button" id="edit-patient">
            Edit Patient
        </a>
        <a class="btn btn-outline-primary" href="{% url 'visits:visits_patient_id' visid patid %}" role="button">
            Edit This Visit
        </a>
        <a class="btn btn-outline-dark" href="{% url 'patientdata:save_operation' patid %}" role="button">
            Add Operation Details
        </a>
        <!--  -->
        {% if match_lab %}
        <a class="btn btn-outline-success" href="{% url 'labs:print_html' visid %}" role="button">
            Print Perview
            </a> {% else %}

        <a class="btn btn-outline-primary float-right" href="#add_drugs_to_prescription" role="button">
                Please Add Drugs 
            </a> {% endif %}
        <br><br>
        <hr>
    </div>

    <form method="post" enctype="multipart/form-data">{% csrf_token %}
        <!--  -->
        <div class="float-left" style="width: 30%;height: 100%;">
            <br>
            <div style="background-color: pink;">
                {{save_medicine_form.non_field_errors}}
            </div>

            {{ lab_form.name.label_tag }} {% render_field lab_form.name %} <br>
            <!--  -->
            <!-- {{ lab_form.result.label_tag }} {% render_field lab_form.result %} <br> -->
            <!--  -->
            {{ lab_form.image.label_tag }} {{ lab_form.image }}
            <br>
            <!--  -->
            {{ lab_form.file.label_tag }} {% render_field lab_form.file %} <br>

            <hr>
            <button type="submit" class="btn btn-outline-dark">
                Add
            </button>

        </div>
        <br>
        <div class="float-right" style="width: 65%; height: 100%; border-style: outset; border-radius: 20px; border-color: #aab5af; box-shadow: 2px 2px 4px 4px grey;">
            <br> {% render_table lab_table %}
        </div>

    </form>

</div>

{% endblock %}

<!--  -->
{% block scripts %}
<script>
    var addDrug = new Vue({
        el: '#add-drug',
        delimiters: ['[[', ']]'],
        data: {
            plan: '',
            name: '',
        },
        computed: {
            // changeLanguage: function(){
            //     this.plan = navigator.language;// 
            //     console.log('plan-changes=' + this.plane);
            //     return this.plan;
            // }
        },
    })
</script>


{% endblock %}

apps/labs/templates/labs/edit_lab_visit.html
{% extends 'index.html' %} {% load crispy_forms_tags %} {% load render_table from django_tables2 %} {% load widget_tweaks %} {% load static %}
<!--  -->
{% block content %}

<div class="container" id="edit-lab">


    <div class="container">
        <h1 style="color: black;">
            <strong>Edit Lab Prescription</strong>
        </h1>
        <!-- <hr> -->
        <!-- <input class="float-right" type="text" name="pages" id="pages"> -->
        <p>
            <h3 style="color: black;">Visit Date : {{ vis_date }}</h3>
        </p>
        <!-- <br> -->
        <hr>
    </div>

    <div class="container" style="width: 100%; height: 100%;">
        <!-- <input type="text" value="{{vis_date}}" name="vis-date" id="vis-date"> -->
        <a class="btn btn-outline-dark" href="{% url 'labs:add_lab_visit' patid visid %}" role="button">
            Return To Add Analysis
        </a>
        <a class="btn btn-outline-dark" href="{% url 'visits:pass_patient_id' patid %}" role="button" id="new-visit">
            New Visit
        </a>
        <a class="btn btn-outline-primary" href="{% url 'patientdata:edit_patient' patid %}" role="button" id="edit-patient">
            Edit Patient
        </a>
        <a class="btn btn-outline-primary" href="{% url 'visits:visits_patient_id' visid patid %}" role="button">
            Edit This Visit
        </a>
        <a class="btn btn-outline-dark" href="{% url 'patientdata:save_operation' patid %}" role="button">
            Add Operation Details
        </a>
        <a class="btn btn-outline-success" href="{% url 'labs:print_html' visid %}" role="button">
            Print Perview
        </a>
        <!-- {% if match_visit %}
        
        
        {% else %}
        
        <a class="btn btn-outline-primary float-right" href="#add_drugs_to_prescription" role="button">
                Please Add Drugs 
            </a>
        
        {% endif %} -->
        <!-- <br> -->
        <hr>
    </div>
    <!-- <div class="container float-right" style="width: 30%; height: 50%;">
        {% if lab.image %}
            <img class="image" src="{{ lab.image.url }}"> 
        {% endif %}
    </div> <br> -->
    <!-- <hr> -->

    <div class="container float-left">
        <form method="post" enctype="multipart/form-data">{% csrf_token %}
            <!--  -->
            <div class="float-left" style="width: 30%;height: 100%;">
                <br>
                <div style="background-color: pink;">
                    {{save_medicine_form.non_field_errors}}
                </div>

                {{ lab_form.name.label_tag }} {% render_field lab_form.name %} <br>
                <!--  -->
                {{ lab_form.result.label_tag }} {% render_field lab_form.result %} <br>
                <!--  -->
                {{ lab_form.resdate.label_tag }} {% render_field lab_form.resdate %} <br>
                <!--  -->
                {{ lab_form.image.label_tag}} {{ lab_form.image }} <br>

                <!-- {% if lab.image %}
                    <div>
                        <img class="image" src="{{ lab.image.url }}"> 
                    </div> <br>
                {% endif %}   -->
                {{ lab_form.file.label_tag}} {{ lab_form.file }} <br>
                <hr>
                <button type="submit" class="btn btn-outline-primary">
                    Update
                </button>
                <!-- <hr> -->
            </div>
            <br>
            <div class="float-right" style="width: 60%; height: 100%; border-style: outset; border-radius: 20px; border-color: #aab5af; box-shadow: 2px 2px 4px 4px grey;">
                <br> {% render_table lab_table %}
            </div>

        </form>
    </div>
</div>

{% endblock %}

<!--  -->
{% block scripts %}
<script>
    var addDrug = new Vue({
        el: '#edit-lab',
        delimiters: ['[[', ']]'],
        data: {
            plan: '',
            name: '',
        },
        computed: {
            // changeLanguage: function(){
            //     this.plan = navigator.language;// 
            //     console.log('plan-changes=' + this.plane);
            //     return this.plan;
            // }
        },
    })
</script>


{% endblock %}

apps/labs/templates/labs/lab_visit_table.html
{% extends 'index.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load render_table from django_tables2 %} 

{% block content %}

<!-- <div class="align-content-center" style="background-color:transparent; width: 1300px; height: 900px; margin: 20px; padding: 10px; border-style: outset; border-radius: 20px; border-color: #aab5af; box-shadow: 2px 2px 4px 4px grey; display: grid;" id="save-visits-div"> -->
  <p class="float-left">
    <h1><strong>Add Lab Analysis Prescription </strong></h1>
  </p>
  <form class="form-inline mt-2 mt-md-0" method="GET" action="{% url 'labs:lab_visit_table' %}">

    <input class="form-control mr-sm-2" type="number" name='pageno' placeholder="Edit pagination pages here.." value="{{request.GET.pageno}}" aria-label="Search">
    <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
    
  </form>
  <br><br>
  {% render_table lab_visit_table %}
<!-- </div> -->
  
{% endblock %}
