apps/patientdata/urls.py
from django.urls import path  # defs
# from clinic.views.home import homepage
from .views import (save_patient, edit_patient, table_patient)
from .operations import save_operation, edit_operation, operation_table
# from clinic.views import visits, medicine, prescription
# from clinic.views.search import search_patient, search_visit, search_date, search_only
# from clinic.views.calculations import (calculate_income, calculate_day_income, 
#                                         calculate_month_income, calculate_year_income)

app_name = 'patientdata'
urlpatterns = [

    # for patient
    path('create/patient/', save_patient, name='save_patient'),
    path('edit/patient/<int:id>/', edit_patient, name='edit_patient'),
    path('table/patients/', table_patient, name='table_patient'),
    # path('patient/details/by/barcode/<str:barcode>/', patient_details, name='patient_details'),
    
    # for operations
    path('add/operation/details/<int:patient_id>/', save_operation, name='save_operation'),
    path('add/operation/details/for/patient/<int:patient_id>/id/<int:id>/', edit_operation, name='edit_operation'),
    path('operation/table/', operation_table, name='operation_table'),
    
    # path('edit/visit/<int:id>/', visits.edit_visits, name='edit_visits'),
    # path('table/visits/', visits.table_visits, name='table_visits'),
    # path('export/table/', visits.export_table, name='export_table'),

    #
    # path('drug/patient/<int:patient_id>/visit/<int:visit_id>/',
    #     medicine.save_medicine, name='save_medicine'),
    #
    # path('add/prescription/patient/<int:patient_id>/visit/<int:visit_id>/',
    #     medicine.add_new, name='add_new'),
    #
    # path('patient/<int:patient_id>/visit/<int:visit_id>/drug/<int:id>/', 
    #     medicine.edit_medicine, name='edit_medicine'),
    
    #
    # path('patient/<int:patient>/visit/<int:visit>/delete/drug/<int:id>/', medicine.delete_medicine, name='delete_medicine'),
    # path('table/medicine/', medicine.table_medicine, name='table_medicine'),
    
    #
    # path('search/patient/', search_patient, name='search_patient'),
    # path('search/visit/', search_visit, name='search_visit'),
    # path('search/date/', search_date, name='search_date'),
    # path('search/only/date/', search_only, name='search_only'),

    #
    # path('income/day/<int:day>/<int:month>/<int:year>/', calculate_income, name='day_income'),
    # path('income/month/<int:day>/<int:month>/<int:year>/', calculate_income, name='month_income'),
    # path('income/year/<int:year>/', calculate_income, name='year_income'),
    # # path('income/day/', calculate_income, name='calculate_day_income'),
    # # path('income/month/', calculate_income, name='calculate_month_income'),
    # path('income/day/', calculate_day_income, name='calculate_day_income'),
    # path('income/month/', calculate_month_income, name='calculate_month_income'),
    # path('income/year/', calculate_year_income, name='calculate_year_income'),
    
    # #
    # path('prescription/visit/<int:visit_id>/', prescription.get_pdf, name='get_pdf'),
    # # This is a good one for printing prescription
    # path('print/visit/<int:visit_id>/', prescription.print_html, name='print_html'),
    # #
    # path('pdf/', prescription.some_view, name='some_view'),

]   

apps/presenthistory/urls.py
from django.urls import path
from .views import *


app_name = "presenthistory"
urlpatterns = [

    # Present History section
    path('create/present/history/patient/<int:patient_id>/visit/<int:visit_id>/',
        save_present_hist,
        name='save_present_hist'),

    path('present/history/patient/<int:patient_id>/visit/<int:visit_id>/edit/<int:id>/', 
        edit_present_hist, 
        name="edit_present_hist"),   

    path('present/history/table/',
        table_present_hist,
        name='table_present_hist'),
    #
    path('delete/present/history/<int:id>/',
        delete_history, 
        name="delete_history"),

    #
    path('present/history/patient/<int:patient_id>/',
        patient_history_table,
        name="patient_history_table"),
    #
    path('present/history/visit/<int:visit_id>/',
        visit_history_table, 
        name="visit_history_table"),

    #
    path('add/present/history/', 
        table_add_present_hist, 
        name="table_add_present_hist"),

]

apps/search/urls.py
from django.urls import path
from .views import *

app_name= "search"

urlpatterns = [

    #
    path('search/patient/', search_patient, name='search_patient'),
    path('search/visit/', search_visit, name='search_visit'),
    path('search/date/', search_date, name='search_date'),
    path('search/only/date/', search_only, name='search_only'),

    #
    # path('income/day/<int:day>/<int:month>/<int:year>/', calculate_income, name='day_income'),
    # path('income/month/<int:day>/<int:month>/<int:year>/', calculate_income, name='month_income'),
    
    # path('income/year/<int:year>/', calculate_income, name='year_income'),
    
    # path('income/day/', calculate_income, name='calculate_day_income'),
    # path('income/month/', calculate_income, name='calculate_month_income'),
    
    # path('income/day/', calculate_day_income, name='calculate_day_income'),
    # path('income/month/', calculate_month_income, name='calculate_month_income'),
    # path('income/year/', calculate_year_income, name='calculate_year_income'),
    

]

apps/visits/urls.py
from django.urls import path  
from .views import *


app_name = 'visits'
urlpatterns = [
  
    # for visit
    path('create/visit/patient/<int:id>/', 
        pass_patient_id, name='pass_patient_id'),
    path('edit/visit/<int:id>/patient/<int:patient_id>/', 
        visits_patient_id, name='visits_patient_id'),
    
    # path('edit/visit/<int:id>/', visits.edit_visits, name='edit_visits'),
    path('table/list/all/visits/', table_visits, name='table_visits'),
    path('export/table/', export_table, name='export_table'),
   
]

metclinic/urls.py
# from os import name
from .utils import backup
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls import url
import debug_toolbar

from .utils import talk_with_reg
from apps.home.views import frontpage

urlpatterns = [
    path('admin/', admin.site.urls),

    # Frontpage 
    path('', frontpage, name='frontpage'),

    path('backup/', backup, name='backup'),
    
    #
    path('lab/', include('apps.labs.urls', namespace='labs')),
    path('patientdata/', include('apps.patientdata.urls', namespace='patientdata')),
    path('pasthistory/', include('apps.pasthistory.urls', namespace='pasthistory')),
    path('presenthistory/', include('apps.presenthistory.urls', namespace='presenthistory')),

    path('revisitdrug/', include('apps.revisitdrug.urls', namespace='revisitdrug')),
    path('revisits/', include('apps.revisits.urls', namespace='revisits')),
    
    path('search/', include('apps.search.urls', namespace='search')),
    
    path('reports/', include('apps.reports.urls', namespace='reports')),
    path('visits/', include('apps.visits.urls', namespace='visits')),
    path('medicine/', include('apps.visitdrug.urls', namespace='visitdrug')),

    path('any/', talk_with_reg, name='talk_with_reg'),
    path('__debug__/', include(debug_toolbar.urls)),


    # the next two linesare for (DEBUG=False) to static works without any problem
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),

]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/css.html
{% load static %}

<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css"> -->

<link rel="stylesheet" href="{% static 'css/bulma.min.css' %}">

<link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}">

<link rel="icon" type="image/png" href="{% static 'favicon/favicon.ico' %}">
<!-- <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> -->
<link rel="stylesheet" href="{% static 'css/bootstrap07.min.css' %}">

<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

<link rel="stylesheet" href="{% static 'css/cloudflare-icon.min.css' %}">

<link rel="stylesheet" href="{% static 'css/style07.css' %}">
<link rel="stylesheet" href="{% static 'css/all.css' %}">


<style>
    /* for printing a table */
    
    @media print {
        table {
            page-break-after: auto
        }
        tr {
            page-break-inside: avoid;
            page-break-after: auto
        }
        td {
            page-break-inside: avoid;
            page-break-after: auto
        }
        thead {
            display: table-header-group
        }
        tfoot {
            display: table-footer-group
        }
    }
    /*  */
    /* for checkboxes */
    
    .switch {
        position: relative;
        display: inline-block;
        width: 60px;
        height: 34px;
    }
    
    .switch input {
        opacity: 0;
        width: 0;
        height: 0;
    }
    
    .slider {
        position: absolute;
        cursor: pointer;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: #ccc;
        -webkit-transition: .4s;
        transition: .4s;
    }
    
    .slider:before {
        position: absolute;
        content: "";
        height: 26px;
        width: 26px;
        left: 4px;
        bottom: 4px;
        background-color: white;
        -webkit-transition: .4s;
        transition: .4s;
    }
    
    input:checked+.slider {
        background-color: #2196F3;
    }
    
    input:focus+.slider {
        box-shadow: 0 0 1px #2196F3;
    }
    
    input:checked+.slider:before {
        /* #returns:checked+.slider:before { */
        -webkit-transform: translateX(26px);
        -ms-transform: translateX(26px);
        transform: translateX(26px);
    }
    /* Rounded sliders */
    
    .slider.round {
        border-radius: 34px;
    }
    
    .slider.round:before {
        border-radius: 50%;
    }
</style>

templates/base/js.html
{% load static %}


<!-- scripts for VUE -->
<script src="{% static 'js/vue.js' %}"></script>
<!-- <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script> -->
<!-- <script src="https://cdnjs.cloudfare.com/ajax/libs/axios/0.19.2/axios.min.js"> -->
<script src="{% static 'js/jquery07.min.js' %}"></script>

<script src="{% static 'js/axios.min.js' %}"></script>

<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>

<script src="{% static 'js/popper07.min.js' %}"></script>

<script src="{% static 'js/bootstrap07.min.js' %}"></script>

<script src="{% static 'js/main07.js' %}"></script>

<!-- <script src="{% static 'js/bootstrap413.min.js' %}"></script> -->

<!-- <script src="{% static 'js/main.js' %}"></script> -->

<script>
    var vue = new Vue({
        el: '#footer-vue',
        delimiters: ['[', ']'],
        data: {
            msg: ' coded by Amr Aly - contact me on 01067174141',
            image: "{% static 'img/k3.jpg' %}",
        },
    });
</script>

templates/base/messages.html


 <section class="section">
            
    {% if messages %}
        {% for message in messages %}
            <article class="message is-{{ message.tags }}">
                <div class="message-body">
                    {{ message }}
                </div>
            </article>
        
        {% endfor %}
    {% endif %}
    <br>
    
</section>


templates/base/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4" id="nav-id">
    <a class="navbar-brand" href="{% url 'patientdata:table_patient' %}">Etman Clinic</a>
    <!-- <a class="navbar-brand" href="/"> <img :src="image"></a> -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <!-- <ul class="navbar-nav ml-auto">
            <form class="form-inline ml-auto">
                <a href="{{request.META.HTTP_REFERER}}" class="btn btn-outline-warning ml-2">
                    << </a>
            </form>
        </ul> -->
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{request.META.HTTP_REFERER}}">
                    <span class="fa fa-backward"> Back </span> </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'patientdata:save_patient' %}" class="navbar-item">
                    <span class='fa fa-user-plus'> Add New Patient</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'presenthistory:table_add_present_hist' %}" class="navbar-item">
                    <span class='fa fa-book-medical'> Add Present History</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'patientdata:operation_table' %}" class="navbar-item">
                    <span class='fa fa-procedures'> All Operation Details</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'patientdata:table_patient' %}" class="navbar-item">
                    <span class='fa fa-hospital-user'> All Patients</span>
                </a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'visits:table_visits' %}" class="navbar-item">
                    <span class='fa fa-syringe'></span> All Visits</a>
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            <form class="form-inline ml-auto">
                <!-- <a href="{% url 'talk_with_reg' %}" class="btn btn-outline-secondary">Reg</a> -->
                <a href="{% url 'backup' %}" class="btn btn-outline-success ml-2">Backup </a>
            </form>
            <!-- <li class="nav-item active">
                <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Wellcome: Dr Mohamed Etman
                </a>
            </li> -->
        </ul>

    </div>

</nav>

<!-- <script>
    var vue = new Vue({
        el: '#nav-id',
        delimiters: ['[', ']'],
        data: {
            // msg: ' coded by Amr Aly',
            image: "{% static 'img/k5.png' %}",
        },
    });
</script> -->

templates/base/search_bar.html
{% load i18n %} {% load static %} {% if request.path == 'dashboard' %} {% else %}

<div class="align-content-center" style="background-color:transparent; position: relative; display: inline-block; width: 100%; height: 100%; border-style: outset; border-radius: 20px; border-color: #aab5af; box-shadow: 2px 2px 4px 4px grey; margin: 20px; padding: 20px;"
    id="searchreport-div">
    {% if request.path == day_url or request.path == month_url or request.path == year_url or request.path == only_date_url %}

    <!-- <div class="align-content-center float-right"> -->
    <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{% url 'search:search_only' %}">
        <!-- {% url 'search:search_only' %} -->
        <input class="form-control mr-sm-2" type="text" name='day' placeholder="Search Day..." value="{{request.GET.day}}" aria-label="Search" v-model="day">
        <input class="form-control mr-sm-2" type="text" name='month' placeholder="Search Month..." value="{{request.GET.month}}" aria-label="Search" v-model="month">
        <input class="form-control mr-sm-2" type="text" name='year' placeholder="Search Year..." value="{{request.GET.year}}" aria-label="Search" v-model="year">
        <!--  -->
        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
        <!--  -->
    </form>
    <!-- </div> -->
    <!-- <br><br><br> -->
    <!-- <div class="align-content-center float-left"> -->
    <form class="form-inline mt-2 mt-md-0 float-right" method="GET" action="{% url 'search:search_date' %}">

        <input class="form-control mr-sm-2" type="text" name='from' placeholder="Search Date from ..." value="{{request.GET.from}}" aria-label="Search">
        <input class="form-control mr-sm-2" type="text" name='to' placeholder="Search Date to ..." value="{{request.GET.to}}" aria-label="Search">
        <!--  -->
        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
        <!--  -->
    </form>
    <!-- </div> -->
    {% elif edit_booking_form %}
    <form class="form-inline mt-2 mt-md-0 float-right" method="GET" action="{% url 'booking:table_book' %}">

        <input class="form-control mr-sm-2" type="text" name='d' placeholder="Search Booking Date(y-m-d)..." value="{{request.GET.d}}" aria-label="Search" id="search-book" v-model="date">
        <!--  -->
        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
        <!--  -->
    </form>
    <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{% url 'booking:edit_book' qs.id %}">

        <input class="form-control mr-sm-2" type="text" name='pat' placeholder="Search Patients Name ..." value="{{request.GET.pat}}" aria-label="Search">

        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
    </form>
    {% elif request.path == bookingtable_url or current_date_table or book_date_table or book_table %}
    <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{% url 'booking:table_book' %}">
        <input class="form-control mr-sm-2" type="date" name='d' placeholder="Search Booking Date..." value="{{request.GET.d}}" aria-label="Search" id="search-book">

        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>

    </form>
    <form class="form-inline mt-2 mt-md-0 float-right" method="GET" action="{% url 'booking:table_book' %}">
        <input class="form-control mr-sm-2" type="text" name='p' placeholder="Search Patient Name ..." value="{{request.GET.p}}" aria-label="Search">

        <input class="form-control mr-sm-2" type="date" name='pd' placeholder="Search patient date..." value="{{request.GET.pd}}" aria-label="Search">

        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search Patient</button>
    </form>
    {% elif request.path == '/booking/create/booking/date/' %}
    <form class="form-inline mt-2 mt-md-0 float-right" method="GET" action="{% url 'booking:table_book' %}">

        <input class="form-control mr-sm-2" type="date" name='d' placeholder="Search Booking Date..." value="{{request.GET.d}}" aria-label="Search" id="search-book" v-model="date">

        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>

    </form>
    <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{% url 'booking:save_book'  %}">

        <input class="form-control mr-sm-2" type="text" name='pat' placeholder="Search Patients Name ..." value="{{request.GET.pat}}" aria-label="Search">

        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>

    </form>
    {% else %}
    <!-- table_patient or table_patient_search -->
    <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{% url 'search:search_patient' %}">

        <input class="form-control mr-sm-2" type="text" name='ph' placeholder="Search Phone & Mobile..." value="{{request.GET.ph}}" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
    </form>
    <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{% url 'search:search_patient' %}">
        <input class="form-control mr-sm-2" type="text" name='card' placeholder="Search Card ID..." value="{{request.GET.card}}" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
    </form>
    <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{% url 'search:search_patient' %}">
        <input class="form-control mr-sm-2" type="text" name='q' placeholder="Search Name & Address..." value="{{request.GET.q}}" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
    </form>
    <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{% url 'search:search_patient' %}">
        <input class="form-control mr-sm-2" type="number" name='pid' placeholder="Search Patient ID..." value="{{request.GET.pid}}" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
    </form>
    <form class="form-inline mt-2 mt-md-0 float-left" method="GET" action="{% url 'search:search_visit' %}">

        <input class="form-control mr-sm-2" type="number" name='vis' placeholder="Search Visits No..." value="{{request.GET.vis}}" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
    </form>

    {% endif %}
</div>
{% endif %} {% block scripts %}
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>

<!-- <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script> -->
<!-- <script type="text/javascript" src="{% static 'js/bootstrap4.0.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.bundle.js' %}"></script> -->

<script type="text/javascript" src="{% static 'js/vue.js' %}"></script>
<script type="text/javascript" src="{% static 'js/axios.min.js' %}"></script>

<script type="text/javascript">
    // $(document).ready(function() {
    //     $('#search-book').datepicker({
    //         dateformat: "yy-mm-dd",
    //     });
    // })
</script>
<script>
    var reportSearch = new Vue({
        el: '#searchreport-div',
        delimiters: ['[[', ']]'],
        data: {
            year: '',
            month: '',
            day: '',
        },
    })
</script>
{% endblock %}

templates/base/search_bar_old.html
<!-- div for searh events date -->
<div class="content" style="background-color:transparent; height: 100%; width: 100%; margin: 30px;
padding: 10px; border-style: outset; border-radius: 20px; border-color: #aab5af; box-shadow: 2px 2px 4px 4px darkgray;" id="search-div" name="mydiv">
    <form class="form-inline mt-2 mt-md-0" method="GET" action="#">
        <input class="form-control mr-sm-2" type="text" name='from' placeholder="Search Event Date from ..." value="{{request.GET.from}}" aria-label="Search">
        <input class="form-control mr-sm-2" type="text" name='to' placeholder="Search Event Date to ..." value="{{request.GET.to}}" aria-label="Search">
        <button class="btn btn-secondary my-2 my-sm-0" type="submit" hidden>Search</button>
    </form>









</div>